apiVersion : v1
kind: Service
metadata:
  name: simplybyte-frontend
spec:
  type: LoadBalancer
  selector:
    app: simplybyte-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081